homeassistant:
  name: Дом
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  packages: !include_dir_named packages/
  whitelist_external_dirs:
    - /config
    - /config/file
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1/32
        - 172.0.0.0/24

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources:
    # HACS
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: js
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
      type: js
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    # Custom
    - url: /local/lovelace/counter-card.js
      type: js
    - url: /local/lovelace/hasl-departure-card.js
      type: js
    - url: /local/lovelace/hasl-trafikstatus-card.js
      type: js
    - url: /local/lovelace/chart-colors.js
      type: js
    - url: /local/lovelace/mm2-clock-card.js
      type: module

system_health:

config:

conversation:

sun:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3

mobile_app:

ios:

automation: !include automation.yaml
script: !include script.yaml
input_boolean: !include input_boolean.yaml

person:

# zeroconf:
# ssdp:
# default_config:
# customize_glob:
# discovery:
# updater:
# cloud:
# history_graph:
