homeassistant:
  name: Дом
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  packages: !include_dir_named packages/
  whitelist_external_dirs:
    - /config
    - /config/file
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1/32
        - 172.0.0.0/24

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

system_health:

config:

conversation:

sun:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3

mobile_app:

ios:

automation: !include automation.yaml
script: !include script.yaml
input_boolean: !include input_boolean.yaml

person:

# zeroconf:
# ssdp:
# default_config:
# customize_glob:
# discovery:
# updater:
# cloud:
# history_graph:
