# Кастомизация
homeassistant:
  customize:
    # Освещение
    light.kitchen:
      friendly_name: Кухня Люстра
      icon: mdi:ceiling-light


# Yeelight
yeelight:
  devices:
    192.168.1.x:
      name: kitchen


# Таймер
timer:
  kitchen_auto:
    duration: '00:00:01'
  kitchen_manual:
    duration: '01:00:00'


input_boolean:
  # Вкл / выкл автоматизации освещения в Lovelace
  kitchen_automation:
    name: Кухня
    initial: on
    icon: mdi:home-automation


# Автоматизации
automation:
  # Включение при обнаружении движения
  - alias: kitchen_light_on_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_kitchen
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('sensor.outdoor_illuminance') | int < 2000 }}"
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: state
          entity_id: timer.kitchen_manual
          state: 'idle'
    action:
      - service: timer.start
        entity_id: timer.kitchen_auto
      - service: light.turn_on
        entity_id: light.kitchen
        data_template:
          brightness_pct: >
            {% if now().isoweekday() < 6 %}
              {% if now().hour >= 7 and now().hour < 22 %} 100
              {% elif now().hour >= 0 and now().hour < 7 %} 1
              {% elif now().hour >= 22 and now().hour < 24 %} 10
              {% endif %}
            {% else %}
              {% if now().hour >= 9 and now().hour < 22 %} 100
              {% elif now().hour >= 7 and now().hour < 9 %} 10
              {% elif now().hour >= 0 and now().hour < 7 %} 1
              {% elif now().hour >= 22 and now().hour < 24 %} 10
              {% endif %}
            {% endif %}
          color_temp: >
            {% if now().hour >= 0 and now().hour < 7 %} 588
            {% else %} 250
            {% endif %}


  # Выключение без движения днем
  - alias: kitchen_light_off_day_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_kitchen
        to: 'off'
        for:
          minutes: 5
    condition:
      - condition: and
        conditions:
          - condition: time
            after: '06:00:00'
            before: '23:00:00'
          - condition: state
            entity_id: light.kitchen
            state: 'on'
          - condition: state
            entity_id: timer.kitchen_manual
            state: 'idle'
    action:
      - service: timer.start
        entity_id: timer.kitchen_auto
      - service: light.turn_off
        entity_id: light.kitchen


  # Выключение без движения ночью
  - alias: kitchen_light_off_night_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_kitchen
        to: 'off'
        for:
          minutes: 1
    condition:
      - condition: and
        conditions:
          - condition: time
            after: '23:00:00'
            before: '06:00:00'
          - condition: state
            entity_id: light.kitchen
            state: 'on'
          - condition: state
            entity_id: timer.kitchen_manual
            state: 'idle'
    action:
      - service: timer.start
        entity_id: timer.kitchen_auto
      - service: light.turn_off
        entity_id: light.kitchen


  # Выключение после остановки таймера
  - alias: kitchen_light_off_timer
    initial_state: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.kitchen_manual
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: light.kitchen
            state: 'on'
          - condition: template
            value_template: "{{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.motion_sensor_kitchen.last_changed)) | int > 600 }}"
    action:
      - service: timer.start
        entity_id: timer.kitchen_auto
      - service: light.turn_off
        entity_id: light.kitchen


  # Включение по одинарному клику
  - alias: kitchen_light_on_switch_click
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_kitchen
          event: 1002
    condition:
      - condition: state
        entity_id: light.kitchen
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data_template:
          brightness_pct: >
            {% if now().hour >= 7 and now().hour < 22 %} 100
            {% elif now().hour >= 22 and now().hour < 24 %} 10
            {% elif now().hour >= 0 and now().hour < 7 %} 1
            {% endif %}
          color_temp: >
            {% if now().hour >= 0 and now().hour < 7 %} 588
            {% else %} 250
            {% endif %}


  # Выключение по одинарному клику
  - alias: kitchen_light_off_switch_click
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_kitchen
          event: 1002
    condition:
      - condition: state
        entity_id: light.kitchen
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.kitchen


  # Включение 25% яркости / 4000K по двойному клику
  - alias: kitchen_light_25_switch_double_click
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_kitchen
          event: 1004
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data_template:
          brightness_pct: 25
          color_temp: 250


  # Включение 100% яркости / 4000K по длинному нажатию
  - alias: kitchen_light_100_switch_long_press
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_kitchen
          event: 1001
    action:
      - service: light.turn_on
        entity_id: light.kitchen
        data_template:
          brightness_pct: 100
          color_temp: 250


  # Запуск таймера при включении / выключении вручную
  - alias: kitchen_timer
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.kitchen
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: timer.kitchen_auto
            state: 'idle'
          - condition: state
            entity_id: alarm_control_panel.ha_alarm
            state: 'disarmed'
    action:
      - service: timer.cancel
        entity_id: timer.kitchen_manual
      - service: timer.start
        entity_id: timer.kitchen_manual


  # Уменьшение яркости в заданное время
  - alias: kitchen_light_decrease
    initial_state: true
    trigger:
      - platform: time
        at: '22:00:00'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: light.kitchen
            state: 'on'
          - condition: state
            entity_id: timer.kitchen_auto
            state: 'idle'
    action:
      - service: timer.start
        entity_id: timer.kitchen_auto
      - service: light.turn_on
        entity_id: light.kitchen
        data_template:
          brightness_pct: 10
          color_temp: 250
          transition: 3


  # Увеличение яркости в заданное время
  - alias: kitchen_light_increase
    initial_state: true
    trigger:
      - platform: time
        at: '07:00:00'
    condition:
      - condition: state
        entity_id: light.kitchen
        state: 'on'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: timer.start
        entity_id: timer.kitchen_auto
      - service: light.turn_on
        entity_id: light.kitchen
        data_template:
          brightness_pct: 100
          color_temp: 250
          transition: 3


  # Включение / выключение автоматизации переключателем в Lovelace
  - alias: kitchen_automation_on_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.kitchen_automation
    action:
      - service: timer.cancel
        entity_id: timer.kitchen_manual
      - service_template: >
          {% if is_state('input_boolean.kitchen_automation', 'on') %}
            automation.turn_on
          {% else %}
            automation.turn_off
          {% endif %}
        entity_id:
          - automation.kitchen_light_on_motion
          - automation.kitchen_light_off_day_motion
          - automation.kitchen_light_off_night_motion
          - automation.kitchen_light_decrease
